server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_6b4b7451a995
    token: lyz1010
    app-id: wx18c00547ebbe5c9e
    appsecret: 7e7159829db450c61a0a4f23a80c479d
    template_id: wCASo3Ra9WJrmKp6g8Au2KOw9i2n241UZG-D5Flhy7I

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 2021000147677741
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCPFJek8uipE9LzgGho8Sab5B/Efc5G4RcwGADiJqr1Rg4uwKb391mskn0Ap64VTyoEgHh9liEHfUOnZTHW0i2glpdpM3jVY2vvLGN4X8sklFM+d/0hFIqjDa/jOVgtx7Xag2eh24xSUQRIwmLvqiB55nkgknUP7vIS4gGT0cEb3iOgz7MfG/bO5o4rHc43ETZO/2/7+edJp+alLmngHp6yRa5Ji5NWK5cynP8Mdi+jKsOEs4Hx8I69Kpd7nvNlewCWdkFMeQvoTwblN5osrup5FdaObnZoA81Qotyg4k7in1W5me6zBt1a6VVJK3HfTkSTr0gJp6r9/q3AnFThHos7AgMBAAECggEAEEny3ad9z0nfeTNEL7ZMg/DboP4FjtIvVp1U9GocimHYWYA7Qf2Z6uiebIWqbuidSvfpP7rotbaQDi2aF+/DnAWo5SQj/H8eGZN/G4QkV1y/gVwdqDdzdQ6o2IB9xnB3BpJxKN8awYBRsYrXwpsmqVoQriGeTBsS2g16yn5VsrtSth18wZmjmnYIF0Tyi0XE6BsMqWtuAE4iRu/QALqzaX/MXtQiZqXKvNjKMWpHXn4p20SvWjto6fa+67xK52bxKw+/AhKJrCl7cS4i2MEcgm+DzaXJRw1kq3T3ZWQqRzRctMO7Xo1VFPycRYOfme8+5kHorhGb0xhs9I+aVoeTwQKBgQDOP+lp/venPQQSiHzQBjd4zkYV1udzaUc+4Mqj5iwe8obOqfvFeW6SwI5xyHV5WrdCV3NubOQ4VVbqYckdVYhPeLe3uyawyFeJpGeoEqqjpshV2BvkNVdr6Z1ifWKkzWos5OPO1nxI/AjHfJspSzLrL5l5UwA0BCtufzqgca5N4QKBgQCxl+3FIA9FTqVsY/lrtNZNjEEY77bTaNStfqpJPAq34EzcK6xyU3NNcGRLp48ujbVWPOmFTONUeKa7UuNvnizvA7Rg8uK22bmsTmFBTAKnqjEEDVEh73fKQ6iQ4AXEHN8b0ojln+w1haAtGrHweyrdIX4eCwRQ5mVp1jT3PFnkmwKBgQCa9whQnMLExCKALk7hGhqpyQp9tEeYvnxKcSmwNevmoMDLHIrQF+oNl2IvebdSI+fXj89qI6Th8rToS+qJAM/3LjOTd6mdYBntkDpV3Ria92BEp6hlMfLqYM/gxWbNfo2NB7lmml8tkzihci0+vIKYlN4Se1uGua9MSYnqLSAS4QKBgAZPqOJ9fi1vWw+cCewa9BazakjRlAS1UAGOY8zQdm0Mao7Uen9hmdJhsR7DKKJ15MDYz0+uaNHCq+IyUuTPkTc5QXrEhuwKlr+Z1Xj1k46TzMQhGQYEtZQZjW8AlxPeFsutUrIeWc2ZHxUbQsGSDvbmzs2QhKm/VlFJjH5Qxb0LAoGBALxFHhXAmhiNb6yNzFIil9FC4W+bMz1ZaMmItEn/8voADLhqMSwgoC/u/XJH3FrquaXvbHEWzdmaVamwqK86qwVRAKgahR0hfxr47gaEO9oNL/MNoirA/NIapEOkG01El9oJVbVWPQmB0/xq3zvA4kP76bneS24jXD8HhssQ/Eu/
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApUwCEXSpgsqk/w8vBBuH5SsFSUc2i3d3u2tTFRPLxzIfM9R4T5iDhjYXfSKmWyiTprq1kEA/ItuWuJP4Za/H76FfHyZ+89vYzJ5gKWfBe/04AlTnv530J7T3N1gy7TpfrlbjFqgNcoAB3yAlbdypPMhdkTKdSqI/7hnIOZlR0glI8hWd4lArqKl9vl+0USrpWFP04hBU5sdiJxcmA517H4DENzLUm1UjbsP+zGBrs/EQgKfAPIsjXdH293h2GUU1cMZkswpTaaFVzSBpJriNIPUNh4HxvvbMrlLaZmvV89C3sq60adScY4Z5eMY8Gtz856aVQ2Dzae51PaS/1VicwwIDAQAB
  notify_url: http://lyz1010.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://www.xiaohongshu.com/explore
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml